server:
  port: 8085
spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: mcam_georeference_ms
          uri: https://pokeapi.co
          predicates:
            - Path=/api/v2/pokemon/**